### ISSUE TITLE
Important! Description of Radical

### ISSUE THREAD

**Issue by Linzybear** [jdlrobson/littledailydose#11]
![image](https://user-images.githubusercontent.com/48169900/55674928-ecdc8580-586f-11e9-939a-f612c5c357ba.png)

Description of radical is italicised but not in <> and no change in colour (yet) 
Eg.  Hand & Ground
扌 Hand Radical 
土 Ground Radical

**Comment by jdlrobson** [comment]
Fixed on wiki.
https://littledailydose.com/7-03.html
