### ISSUE TITLE
Table of content is gone?

### ISSUE THREAD

**Issue by Linzybear** [jdlrobson/littledailydose#14]
![image](https://user-images.githubusercontent.com/48169900/55767303-260e2480-5a2d-11e9-83f4-dde310cf8063.png)

**Comment by Linzybear** [comment]
CONTACT is gone too

![image](https://user-images.githubusercontent.com/48169900/55767339-4fc74b80-5a2d-11e9-85a4-1022c626d8c8.png)

**Comment by jdlrobson** [comment]
Fixed https://littledailydose.com/index.html
