### ISSUE TITLE
Notice that many vocabularies are "cut off" at the bottom

### ISSUE THREAD

**Issue by Linzybear** [jdlrobson/littledailydose#25]
![image](https://user-images.githubusercontent.com/48169900/67032923-6f6cba00-f0c9-11e9-9731-4c40e745285b.png)

![image](https://user-images.githubusercontent.com/48169900/67032945-7abfe580-f0c9-11e9-9760-a309f01554ba.png)

![image](https://user-images.githubusercontent.com/48169900/67033004-93300000-f0c9-11e9-82b2-c9881e03ab47.png)

![image](https://user-images.githubusercontent.com/48169900/67033025-a347df80-f0c9-11e9-934a-9493fc7f3a5a.png)

**Comment by kimchihuat** [comment]
I don't understand this 'cut-off', dear
