### ISSUE TITLE
Can we revise the Contact page?

### ISSUE THREAD

**Issue by Linzybear** [jdlrobson/littledailydose#7]
I'm thinking we can revise the footer menu to DISCOVER | LEARN | CONTACT

![Contact](https://user-images.githubusercontent.com/48169900/55414881-dc9b7200-5520-11e9-8b94-34a9238fc5fa.jpg)

Here's the copy, feel free to edit:

Linz Lim & Jon Robson created A Little Daily Dose,
to spark your interest in learning Chinese.

This is an ongoing project to document and share
their Chinese learning adventures.
Drop them a note if you would like to
contribute a word, point out something wrong
or simply to say Hello.

L. 
linzybearswings@gmail.com
Download her CV (pdf)

J. 
jdlrobson@gmail.com
Visit his website (link)

**Comment by jdlrobson** [comment]
For copy change and content please update the wiki page  !!!

https://github.com/jdlrobson/littledailydose/wiki/About-us/_edit

**Comment by Linzybear** [comment]
![Robsonlim](https://user-images.githubusercontent.com/48169900/55642755-3cdf1d80-5786-11e9-9f42-75cd0bd621f3.png)
